### ISSUE TITLE
does it work with modded bios

### ISSUE THREAD

**Issue by souhaiebtar** [intruder16/Y510p-OS-X-Clover-Hotpatch#2]

**Comment by intruder16** [comment]
Yes. It works with modded BIOS.

FYI: I've not tested hotpatching with 10.12.3+. It may not work with 10.13.x. I've been away for a very long time. If you still try it, do let me know the results.

**Comment by souhaiebtar** [comment]
@intruder16  really thank you for responding and all the great work you have done, i got el capitain   fully working on my machine thanks to your work ( but the legacy method , using your other git repo for y510 , which mode dsdt and ssdt file)and @ahmedais help, i still like that one more ( only if it would work  with the sierra or high sierra ),
thank you again, and wish you good luck

**Comment by intruder16** [comment]
Great!

I'll test it on high sierra as soon as i get time.

**Comment by souhaiebtar** [comment]
after testing, it does work on modded bios, it worked with sierra 12.6, usb3 devices work fine but usb2  devices don't connect, i fixed it by  enabling EHC, it was done by commenting  line that put EHC in sleep mode in *SSDT-HACK.dsl* file 
```^^EH01.PSTE = 3``` 
```^^LPCB.FDE1 = 1```   
```^^EH02.PSTE = 3```  
```^^LPCB.FDE2 = 1```,

 just to now i aslo usb *usbinjectall.kext*,

what i understand is that by putting EHC in sleep mode, we force usb2 device to reroute to XHCI which seem to give better performance, but it diddn't work for me, that is why is disabled sleep for EHC,

do you now a better solution, for that, ?

still thanks, again,

i will try to comment in insanelymac forum, with the different step i used to make it work,

**Comment by souhaiebtar** [comment]
it does work on high sierra,
